permalink: /:categories/:title
gems:
- jekyll-redirect-from
auto: true
url: http://www.google.com
name: "Zotero: Better BibTeX"
description: Better BibTeX support for Zotero
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "bootstrap"
