---
"/index.html":
  title: Zotero++
  url: "/index.html"
  project:
    slug: 
    title: Zotero++
  pages:
  - title: pdf
    url: "/pdf.html"
    project:
      slug: 
      title: Zotero++
  - title: Support
    url: "/support.html"
    project:
      slug: 
      title: Zotero++
"/pdf.html":
  title: pdf
  url: "/pdf.html"
  project:
    slug: 
    title: Zotero++
"/support.html":
  title: Support
  url: "/support.html"
  project:
    slug: 
    title: Zotero++
"/ascii-rename/index.html":
  title: ASCII rename
  url: "/ascii-rename/index.html"
  project:
    slug: ascii-rename
    title: ASCII rename
"/auto-index/index.html":
  title: Auto Index
  url: "/auto-index/index.html"
  project:
    slug: auto-index
    title: Auto Index
"/link-local-files/index.html":
  title: Link local files
  url: "/link-local-files/index.html"
  project:
    slug: link-local-files
    title: Link local files
"/opds/index.html":
  title: Zotero OPDS server
  url: "/opds/index.html"
  project:
    slug: opds
    title: Zotero OPDS server
"/report-customizer/index.html":
  title: Report Customizer
  url: "/report-customizer/index.html"
  project:
    slug: report-customizer
    title: Report Customizer
