---
"/index.html":
  title: Zotero++
  url: "/index.html"
  project:
    slug: 
    title: Zotero++
  pages:
  - title: pdf
    url: "/pdf.html"
    project:
      slug: 
      title: Zotero++
  - title: Support
    url: "/support.html"
    project:
      slug: 
      title: Zotero++
"/pdf.html":
  title: pdf
  url: "/pdf.html"
  project:
    slug: 
    title: Zotero++
"/support.html":
  title: Support
  url: "/support.html"
  project:
    slug: 
    title: Zotero++
"/ascii-rename/index.html":
  title: ASCII rename
  url: "/ascii-rename/index.html"
  project:
    slug: ascii-rename
    title: ASCII rename
"/auto-index/index.html":
  title: Auto Index
  url: "/auto-index/index.html"
  project:
    slug: auto-index
    title: Auto Index
"/better-bibtex/index.html":
  title: Better BibTeX
  url: "/better-bibtex/index.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
  pages:
  - title: Change log
    url: "/better-bibtex/CHANGELOG.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Citation Keys
    url: "/better-bibtex/citation-keys.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Collected Notes
    url: "/better-bibtex/collected-notes.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Customized Exports
    url: "/better-bibtex/export.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Going hardcore; Zotero as a BibTeX manager
    url: "/better-bibtex/hardcore.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Niceties
    url: "/better-bibtex/niceties.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Push/Pull Export
    url: "/better-bibtex/pull-export.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
  - title: Unicode problems
    url: "/better-bibtex/unicode.html"
    project:
      slug: better-bibtex
      title: Better BibTeX
"/better-bibtex/CHANGELOG.html":
  title: Change log
  url: "/better-bibtex/CHANGELOG.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/citation-keys.html":
  title: Citation Keys
  url: "/better-bibtex/citation-keys.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/collected-notes.html":
  title: Collected Notes
  url: "/better-bibtex/collected-notes.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/export.html":
  title: Customized Exports
  url: "/better-bibtex/export.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/hardcore.html":
  title: Going hardcore; Zotero as a BibTeX manager
  url: "/better-bibtex/hardcore.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/niceties.html":
  title: Niceties
  url: "/better-bibtex/niceties.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/pull-export.html":
  title: Push/Pull Export
  url: "/better-bibtex/pull-export.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/better-bibtex/unicode.html":
  title: Unicode problems
  url: "/better-bibtex/unicode.html"
  project:
    slug: better-bibtex
    title: Better BibTeX
"/link-local-files/index.html":
  title: Link local files
  url: "/link-local-files/index.html"
  project:
    slug: link-local-files
    title: Link local files
"/opds/index.html":
  title: Zotero OPDS server
  url: "/opds/index.html"
  project:
    slug: opds
    title: Zotero OPDS server
"/report-customizer/index.html":
  title: Report Customizer
  url: "/report-customizer/index.html"
  project:
    slug: report-customizer
    title: Report Customizer
